// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ospnuclymrxjoqwyolfn.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im9zcG51Y2x5bXJ4am9xd3lvbGZuIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQyMjA4MTYsImV4cCI6MjA1OTc5NjgxNn0.oKyrWC5sdoA9Cyrl5fZDz9eWGqrN3ORqNdPMQHJJjkQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});